### ISSUE TITLE
关于后台运行和UAC的建议

### ISSUE THREAD

**Issue by poromony** [yixxqg2023/yixxqg#4]
（1）建议主程序可以配置为关闭窗口后最小化到系统托盘；
（2）主程序每次打开Chrome的时候系统会进行UAC授权，经确认在属性中没有勾选“以管理员权限运行”；
谢谢~

**Comment by yixxqg2023** [comment]
> （1）建议主程序可以配置为关闭窗口后最小化到系统托盘； （2）主程序每次打开Chrome的时候系统会进行UAC授权，经确认在属性中没有勾选“以管理员权限运行”； 谢谢~

1）新版本已经完成这个功能；
2）测试用的电脑不需要UAC授权，可以尝试手动勾选并对整个chrome文件夹右键“管理员取得所有权”

感谢反馈
